### ISSUE TITLE
Filter 

### ISSUE THREAD

**Issue by prasuna61** [ICE10ICE/pet-shop#1]
Expand the filter design in user dashboard

**Comment by Samigyalami** [comment]
![filter ss](https://github.com/ICE10ICE/pet-shop/assets/138389599/42dceb61-c921-4ea2-b77d-25715185f7f9)
![filter 2](https://github.com/ICE10ICE/pet-shop/assets/138389599/64279e40-4996-4745-a529-0345e721e048)
In first picture we can see that the filter components are very close to each . After figuring out the issue i have expand the filter section. 

Done and updated.
